### ISSUE TITLE
How to use it to solve the problem in batches?

### ISSUE THREAD

**Issue by rangwani-harsh** [jayanthkoushik/torch-gel#7]
Hi @jayanthkoushik , You have provided an example of how to use the library for solving for a single instance. Is there support for solving the problem in a batches? 

Thanks for your time and support

**Comment by jayanthkoushik** [comment]
Hi, do you mean obtaining solution paths (for different regularization values)? Yes, that is supported. Please see https://github.com/jayanthkoushik/torch-gel#solution-paths.

**Comment by rangwani-harsh** [comment]
No I mean solving the optimization problem for a batch of examples together i.e. passing the input Y to be of the shape [no_of_samples, feature_len]. Although I am not sure of the existence of such an algorithm

**Comment by jayanthkoushik** [comment]
multiple Y (feature_len) can be solved separately because the solutions are independent (direct solving is not supported)
